### ISSUE TITLE
301 on old website

### ISSUE THREAD

**Issue by wouterbulten** [wouterbulten/acais-website#3]
We need to add a 301 redirect on the old website

**Comment by TNieuwdorp** [comment]
For this we will need to edit the .htaccess, which I think can only be altered by direct ftp access to the server, or by installing a wordpress plugin (which would require ftp access as well). Have you got that access or shall I stalk the Web Committee about this?

**Comment by wouterbulten** [comment]
Which plugin have you found? I think I can install plugins :)

**Comment by TNieuwdorp** [comment]
https://wordpress.org/plugins/redirection/installation/
